# Generated by Django 2.0.2 on 2018-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2018)),
                ('episodes', models.IntegerField(default=1)),
                ('watchedEpisodes', models.IntegerField(default=0)),
                ('inProgress', models.BooleanField(default=False)),
            ],
        ),
    ]
