# Generated by Django 2.0.2 on 2018-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='watchedSeasons',
            field=models.IntegerField(default=0, verbose_name='Watched seasons'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='inProgress',
            field=models.BooleanField(default=False, verbose_name='Currently watching'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='watchedEpisodes',
            field=models.IntegerField(default=0, verbose_name='Watched episodes'),
        ),
    ]
